export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const FACEBOOK_AUTHENTICATION_FAILED = 'FACEBOOK_AUTHENTICATION_FAILED';
export const FACEBOOK_AUTHENTICATION_SUCCESS = 'FACEBOOK_AUTHENTICATION_SUCCESS';
export const API_AUTHENTICATION_FAILED = 'API_AUTHENTICATION_FAILED';
export const API_AUTHENTICATION_SUCCESS = 'API_AUTHENTICATION_SUCCESS';
export const API_AUTHENTICATION_LOGOUT = 'API_AUTHENTICATION_LOGOUT';

// Users
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';

// Trips
export const LOADING_TRIP_DETAILS = 'LOADING_TRIP_DETAILS';
export const LOADING_TRIP_DETAILS_FAILED = 'LOADING_TRIP_DETAILS_FAILED';
export const TRIP_DETAILS_LOADED = 'TRIP_DETAILS_LOADED';

// Technical Action
export const POST_REHYDRATE = 'POST_REHYDRATE';