export const START_FACEBOOK_AUTHENTICATION = 'START_FACEBOOK_AUTHENTICATION';
export const FACEBOOK_AUTHENTICATION_FAILED = 'FACEBOOK_AUTHENTICATION_FAILED';
export const FACEBOOK_AUTHENTICATION_SUCCESS = 'FACEBOOK_AUTHENTICATION_SUCCESS';