export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const FACEBOOK_AUTHENTICATION_FAILED = 'FACEBOOK_AUTHENTICATION_FAILED';
export const FACEBOOK_AUTHENTICATION_SUCCESS = 'FACEBOOK_AUTHENTICATION_SUCCESS';
export const API_AUTHENTICATION_FAILED = 'API_AUTHENTICATION_FAILED';
export const API_AUTHENTICATION_SUCCESS = 'API_AUTHENTICATION_SUCCESS';